[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/offer"
  to = "/offer/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/offer/"
  to = "/offer/index.html"
  status = 200
  force = true
